irrelevant_keywords = {
    "tiktok", "facebook", "instagram", "twitter", "snapchat", "reddit", "youtube",
    "netflix", "hulu", "spotify", "apple music", "soundcloud", "gaming", "fortnite",
    "minecraft", "valorant", "roblox", "league of legends", "taylor swift", "drake",
    "bts", "blackpink", "kpop", "celebrity", "gossip", "memes", "jokes", "funny",
    "movies", "tv shows", "anime", "manga", "fanfic", "romance", "dating", "love",
    "crush", "relationship", "heartbreak", "breakup", "marriage", "wedding", "divorce",
    "parenting", "baby", "pets", "dog", "cat", "food", "recipes", "cooking", "baking",
    "restaurant", "fast food", "shopping", "fashion", "clothing", "makeup", "skincare",
    "beauty", "fitness", "workout", "exercise", "gym", "diet", "weight loss", "mental health",
    "therapy", "self-care", "finance", "money", "stocks", "investing", "crypto", "bitcoin",
    "nft", "real estate", "cars", "motorcycles", "travel", "vacation", "flight", "hotel",
    "airbnb", "beach", "mountain", "holiday", "birthday", "party", "event", "school",
    "exam", "homework", "assignment", "teacher", "classmate", "friend", "bullying", "drugs",
    "alcohol", "smoking", "crime", "murder", "violence", "war", "politics", "president",
    "election", "government", "law", "religion", "god", "atheism", "philosophy", "history",
    "art", "music", "book", "novel", "author", "poetry", "literature", "origami", "quantum physics",
    "beekeeping", "mythology", "conspiracy theories", "tarot cards", "astrology", "zodiac signs",
    "aliens", "ufo", "space exploration", "robotics", "quantum computing",
    "gardening", "composting", "minimalism", "tiny homes", "diy crafts", "thrift shopping",
    "vintage", "antiques", "archaeology", "fossils", "survival skills", "caving", "skydiving",
    "scuba diving", "chess", "board games", "puzzles", "coin collecting", "stamp collecting",
    "languages", "sign language", "calligraphy", "3d printing", "graphic design", "cinematography",
    "voice acting", "puppetry", "mycology", "crystals", "meditation", "lucid dreaming",
    "sleep paralysis", "time travel", "alternate realities", "parallel universe", "foraging",
    "sailing", "martial arts", "parkour", "astrophotography", "haunted places",
    "escape rooms", "karaoke", "fan theories", "barbering", "interior design", "plumbing",
    "carpentry", "knitting", "sewing", "embroidery", "jewelry making", "leather crafting",
    "pottery", "ceramics", "blacksmithing", "welding", "glassblowing", "aquariums",
    "birdwatching", "reptile care", "insect collecting", "model trains", "airsoft", "paintball",
    "geocaching", "treasure hunting", "metal detecting", "watch repair", "lock picking",
    "horology", "weather forecasting", "storm chasing", "cartography", "typography",
    "urban planning", "architecture", "bridge engineering", "forestry", "landscaping",
    "furniture flipping", "auction hunting", "paleontology",
    "deserts", "canyons", "gravity", "magnetism", "friction", "optics", "billiards", "dart games",
    "speedcubing", "yo-yo tricks", "juggling", "ventriloquism", "improv comedy", "stand-up comedy",
    "flash mobs", "parades", "renaissance fairs", "cosplay", "larping", "fan edits",
    "bootleg toys", "mascots", "vintage ads", "internet archives", "retro tech", "obsolete software",
    "typical daydreams", "fictional languages", "imaginary friends", "celebs", "influencer", "streamer", "podcast", "vlogger", "trending", "viral",
    "luxury", "rich", "poor", "jealousy", "envy", "drama", "scandal",
    "zodiac", "horoscope", "astrology", "tarot", "witchcraft", "magic", "spells",
    "dreams", "nightmares", "ghost", "supernatural", "paranormal", "alien", "ufo",
    "conspiracy", "flat earth", "illuminati", "haunted", "cursed",
    "makeover", "nails", "hairstyle", "tattoo", "piercing",
    "dance", "karaoke", "karaoke night", "fan", "stan", "fandom",
    "drinking", "hangover", "party life", "college party", "frat", "sorority",
    "gala", "award show", "oscar", "grammy", "met gala",
    "stream", "livestream", "tournament", "cosplay", "comic con",
    "celebration", "engagement", "anniversary", "baby shower",
    "mall", "boutique", "outfit", "trend", "runway", "styling",
    "hack", "lifehack", "diy", "craft", "interior design", "decor", "furniture",
    "petsitting", "puppy", "kitten", "hamster", "bird", "reptile",
    "zoo", "aquarium", "pet shop", "grooming",
    "karaoke", "idol", "talent show", "competition", "audition",
    "fan edit", "fyp", "reaction", "duet", "stitch",
    "emoji", "slang", "abbreviation", "texting", "emoji meaning",
    "rant", "vent", "overshare", "tea", "spill"
}