services:
  - type: web
    name: gis-chatbot-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    autoDeploy: true

  - type: web
    name: eco-urban
    env: node
    buildCommand: npm install --production=false && npm run build
    startCommand: node index.js
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        value: your-mongodb-uri-here
      - key: NODE_ENV
        value: production